on: [push, pull_request]
name: Linux installation

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      # - name: Install Authoring Dependencies
      #   run: cpanm -n App::ModuleBuildTiny && cpanm -q -n --no-man-pages --installdeps .
      - name: Test and build
        run: |
          # cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage || cat /home/runner/.cpanm/work/*/build.log
          # perl -Mparent -e0 || cpanm parent
          # rm -rf /home/runner/.cpanm/work/*
          cpanm --installdeps . # || cat /home/runner/.cpanm/work/*/build.log
          perl Makefile.PL
          make test
          make dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist-for-installation-test
          path: '*.tar.gz'
          retention-days: 1
  install-linux:
    runs-on: 'ubuntu-latest'
    needs: build
    container:
      image: perl:5.34
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-for-installation-test
      - name: Display the downloaded files
        run: ls -R
      - name: Install in a perl:5.34 container
        run: cpanm *.tar.gz
  install-openbsd:
    runs-on: macos-10.15
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Test and build
        uses: cross-platform-actions/action@v0.0.1
        with:
          operating_system: openbsd
          version: 6.9
          env:
            GITHUB_RUN_ID: github.run_id
          shell: bash
          run: |
            sudo pkg_add github-cli &&
            cpan App::cpanminus &&
            gh run download $GITHUB_RUN_ID &&
            /home/runner/perl5/bin/cpanm --notest --installdeps *.tar.gz &&
            /home/runner/perl5/bin/cpanm -v *.tar.gz

